<a href="https://colab.research.google.com/github/benjouira/python/blob/main/Python(22_10_2021).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

a = np.array(range(10), dtype=float)
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
b = np.arange(0,5,0.75)
b

array([0.  , 0.75, 1.5 , 2.25, 3.  , 3.75, 4.5 ])

In [ ]:
b.ndim

1

In [ ]:
b.size

7

In [ ]:
arr = np.array ([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
arr.shape

(2, 2, 3)

**Import file from Drive**

In [ ]:
from google.colab import drive 
drive.mount("/content/drive")

Mounted at /content/drive


In [ ]:
a = np.loadtxt("/content/drive/MyDrive/matrice.txt")
a

array([[ 26.,  64., 162.],
       [ 30.,  75., 160.],
       [ 62.,  81., 172.]])

In [ ]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.eye(5,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])